FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime

WORKDIR /workspace

RUN apt-get update && apt-get install -y \
    wget \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir runpod minio httpx

# COPY model source
COPY app/infrastructure/pipeline/af2_gamma_eval /workspace/code/af2

RUN if [ -f /workspace/code/af2/requirements.txt ]; then \
    pip install --no-cache-dir -r /workspace/code/af2/requirements.txt; \
    fi

# COPY ONLY af2 weights
COPY Weights/af2/ /workspace/weights/af2/

COPY runpod_worker/handler.py /workspace/handler.py

ENTRYPOINT ["python", "/workspace/handler.py"]
